from django.db import models

class overviewTable(models.Model):
    grade = models.IntegerField(default=0)
    mondayId = models.IntegerField(default=0)
    tuesdayId = models.IntegerField(default=0)
    wednesdayId = models.IntegerField(default=0)
    thursdayId = models.IntegerField(default=0)
    fridayId = models.IntegerField(default=0)

class mondayTable(models.Model):
    gradeId = models.IntegerField(default=0)
    period00Id = models.IntegerField(default=0)
    period01Id = models.IntegerField(default=0)
    period02Id = models.IntegerField(default=0)
    period03Id = models.IntegerField(default=0)
    period04Id = models.IntegerField(default=0)
    period05Id = models.IntegerField(default=0)
    period06Id = models.IntegerField(default=0)
    period07Id = models.IntegerField(default=0)
    period08Id = models.IntegerField(default=0)
    period09Id = models.IntegerField(default=0)
class tuesdayTable(models.Model):
    gradeId = models.IntegerField(default=0)
    period00Id = models.IntegerField(default=0)
    period01Id = models.IntegerField(default=0)
    period02Id = models.IntegerField(default=0)
    period03Id = models.IntegerField(default=0)
    period04Id = models.IntegerField(default=0)
    period05Id = models.IntegerField(default=0)
    period06Id = models.IntegerField(default=0)
    period07Id = models.IntegerField(default=0)
    period08Id = models.IntegerField(default=0)
    period09Id = models.IntegerField(default=0)
class wednesdayTable(models.Model):
    gradeId = models.IntegerField(default=0)
    period00Id = models.IntegerField(default=0)
    period01Id = models.IntegerField(default=0)
    period02Id = models.IntegerField(default=0)
    period03Id = models.IntegerField(default=0)
    period04Id = models.IntegerField(default=0)
    period05Id = models.IntegerField(default=0)
    period06Id = models.IntegerField(default=0)
    period07Id = models.IntegerField(default=0)
    period08Id = models.IntegerField(default=0)
    period09Id = models.IntegerField(default=0)
class thursdayTable(models.Model):
    gradeId = models.IntegerField(default=0)
    period00Id = models.IntegerField(default=0)
    period01Id = models.IntegerField(default=0)
    period02Id = models.IntegerField(default=0)
    period03Id = models.IntegerField(default=0)
    period04Id = models.IntegerField(default=0)
    period05Id = models.IntegerField(default=0)
    period06Id = models.IntegerField(default=0)
    period07Id = models.IntegerField(default=0)
    period08Id = models.IntegerField(default=0)
    period09Id = models.IntegerField(default=0)
class fridayTable(models.Model):
    gradeId = models.IntegerField(default=0)
    period00Id = models.IntegerField(default=0)
    period01Id = models.IntegerField(default=0)
    period02Id = models.IntegerField(default=0)
    period03Id = models.IntegerField(default=0)
    period04Id = models.IntegerField(default=0)
    period05Id = models.IntegerField(default=0)
    period06Id = models.IntegerField(default=0)
    period07Id = models.IntegerField(default=0)
    period08Id = models.IntegerField(default=0)
    period09Id = models.IntegerField(default=0)


class subjectIdTable(models.Model):
    codeRoom = models.CharField(max_length=60)
    codeSubject = models.CharField(max_length=60)
    teacherName = models.CharField(max_length=60)
