# Generated by Django 5.1.2 on 2024-11-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fridayTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeId', models.IntegerField()),
                ('period00', models.CharField(max_length=60)),
                ('period01', models.CharField(max_length=60)),
                ('period02', models.CharField(max_length=60)),
                ('period03', models.CharField(max_length=60)),
                ('period04', models.CharField(max_length=60)),
                ('period05', models.CharField(max_length=60)),
                ('period06', models.CharField(max_length=60)),
                ('period07', models.CharField(max_length=60)),
                ('period08', models.CharField(max_length=60)),
                ('period09', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='mondayTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeId', models.IntegerField()),
                ('period00', models.CharField(max_length=60)),
                ('period01', models.CharField(max_length=60)),
                ('period02', models.CharField(max_length=60)),
                ('period03', models.CharField(max_length=60)),
                ('period04', models.CharField(max_length=60)),
                ('period05', models.CharField(max_length=60)),
                ('period06', models.CharField(max_length=60)),
                ('period07', models.CharField(max_length=60)),
                ('period08', models.CharField(max_length=60)),
                ('period09', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='overviewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('mondayId', models.IntegerField()),
                ('tuesdayId', models.IntegerField()),
                ('wednesdayId', models.IntegerField()),
                ('thursdayId', models.IntegerField()),
                ('fridayId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeRoom', models.CharField(max_length=60)),
                ('codeSubject', models.CharField(max_length=60)),
                ('teacherName', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='thursdayTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeId', models.IntegerField()),
                ('period00', models.CharField(max_length=60)),
                ('period01', models.CharField(max_length=60)),
                ('period02', models.CharField(max_length=60)),
                ('period03', models.CharField(max_length=60)),
                ('period04', models.CharField(max_length=60)),
                ('period05', models.CharField(max_length=60)),
                ('period06', models.CharField(max_length=60)),
                ('period07', models.CharField(max_length=60)),
                ('period08', models.CharField(max_length=60)),
                ('period09', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='tuesdayTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeId', models.IntegerField()),
                ('period00', models.CharField(max_length=60)),
                ('period01', models.CharField(max_length=60)),
                ('period02', models.CharField(max_length=60)),
                ('period03', models.CharField(max_length=60)),
                ('period04', models.CharField(max_length=60)),
                ('period05', models.CharField(max_length=60)),
                ('period06', models.CharField(max_length=60)),
                ('period07', models.CharField(max_length=60)),
                ('period08', models.CharField(max_length=60)),
                ('period09', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='wednesdayTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeId', models.IntegerField()),
                ('period00', models.CharField(max_length=60)),
                ('period01', models.CharField(max_length=60)),
                ('period02', models.CharField(max_length=60)),
                ('period03', models.CharField(max_length=60)),
                ('period04', models.CharField(max_length=60)),
                ('period05', models.CharField(max_length=60)),
                ('period06', models.CharField(max_length=60)),
                ('period07', models.CharField(max_length=60)),
                ('period08', models.CharField(max_length=60)),
                ('period09', models.CharField(max_length=60)),
            ],
        ),
    ]
