# Generated by Django 5.1.2 on 2024-11-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTable', '0002_thurstable_wednestable_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='thursTable',
            new_name='thursdayTable',
        ),
        migrations.RenameModel(
            old_name='wednesTable',
            new_name='wednesdayTable',
        ),
    ]
